@startuml section

== Initialization ==
Alice -> Bob : Authentication Request
Bob -> Alice : Authentication Response

== Repetition == 
Alice -> Bob: Another authtication Request
Alice <-- Bob: another authentication Response

@enduml